- name: Modify HTTP response headers
  hosts: win
  roles:
    - name: iis-custom-headers
      iis_custom_headers:
        - { site: "Default Web Site", name: "X-Frame-Options", value: "SAMEORIGIN", state: "present" }
        - { site: "Default Web Site", name: "X-Powered-By", value: "ASP", state: "absent" }
        - { site: "Default Web Site", name: "X-Powered-By", value: "ASP.NET", state: "absent" }
        - { site: "MySite", name: "Strict-Transport-Security", value: "max-age=31536000", state: "present" }
        - { site: "MySite", name: "X-Frame-Options", value: "SAMEORIGIN", state: "present" }
        - { site: "MySite", name: "X-Powered-By", value: "ASP.NET", state: "present" }
      iis_custom_headers_restart_iis: True