- name: Create IIS site and modify HTTP response headers
  hosts: win
  tasks:
  - name: Create a new application pool in 'Started' state
    win_iis_website:
      name: MySite
      state: started
      port: 80
      ip: {{ private_ip }}
      hostname: mysite.local
      application_pool: DefaultAppPool
      physical_path: C:\inetpub\mysite
      parameters: logfile.directory:C:\inetpub\logs\mysite
    register: win_iis_website
  
  roles:
    - include_role:
      name: iis-custom-headers
      iis_custom_headers:
        - { site: "Default Web Site", name: "X-Frame-Options", value: "SAMEORIGIN", state: "present" }
        - { site: "Default Web Site", name: "X-Powered-By", value: "ASP", state: "absent" }
        - { site: "Default Web Site", name: "X-Powered-By", value: "ASP.NET", state: "absent" }
        - { site: "MySite", name: "Strict-Transport-Security", value: "max-age=31536000", state: "present" }
        - { site: "MySite", name: "X-Frame-Options", value: "SAMEORIGIN", state: "present" }
        - { site: "MySite", name: "X-Powered-By", value: "Konsalt", state: "present" }
      iis_custom_headers_restart_iis: True