---

- debug:
    var: item.name
    verbosity: 1

- debug:
    var: item.value
    verbosity: 1

- debug:
    var: item.state
    verbosity: 1

# Attempted duplicate entries will cause this sort of error:
# Error: Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'X-Frame-Options'
- name: "Add {{ item.name }} custom header."
  win_shell: "Add-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter 'system.webServer/httpProtocol/customHeaders' -name . -value @{name='{{ item.name }}';value='{{ item.value }}'}"
  notify: restart iis
  register: iis_custom_headers_add
  changed_when:
    - iis_custom_headers_add.stderr is defined
    - iis_custom_headers_add.stderr == ''
  failed_when:
    - iis_custom_headers_add.stderr is defined
    - not iis_custom_headers_add.stderr == ''
    - not 'Cannot add duplicate collection entry' in iis_custom_headers_add.stderr
  when:
    - item.name is defined
    - item.value is defined
    - item.state is defined
    - item.state == "present"

- debug:
    var: iis_custom_headers_add
    verbosity: 1

# Attempted removal of non-existent keys warns:
# WARNING: Property . is not found on /system.webServer/httpProtocol/customHeaders at index @{name="X-Frame-Options"}.

# Removing a property where only the key OR value matches throws a warning:
# WARNING: Property . is not found on /system.webServer/httpProtocol/customHeaders at index @{value="DENY";name="X-Frame-Options"}.
- name: "Remove {{ item.name }} custom header."
  win_shell: "Remove-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter 'system.webServer/httpProtocol/customHeaders' -name . -AtElement @{name='{{ item.name }}';value='{{ item.value }}'}"
  ignore_errors: True
  notify: restart iis
  register: iis_custom_headers_remove
  when:
    - item.name is defined
    - item.value is defined
    - item.state is defined
    - item.state == "absent"

- debug:
    var: iis_custom_headers_remove
    verbosity: 1
