---
- name: "Check existing global customHeaders."
  win_shell: "Get-WebConfigurationProperty \
  -pspath 'MACHINE/WEBROOT/APPHOST' \
  -filter 'system.webServer/httpProtocol/customHeaders' \
  -name ."
  register: iis_custom_headers_properties
  changed_when: False

- include: webconfigurationproperty.yml
  with_items:
  - "{{ iis_custom_headers | default(omit) }}"
  when: iis_custom_headers is defined